### ISSUE TITLE
Expose ids in Braintree::ResourceCollection

### ISSUE THREAD

**Issue by amree** [braintree/braintree_ruby#109]
Hello

May I know why Braintree didn't expose `@ids` in the returned result for `search` API? For e.g:

```
search_results = Braintree::Transaction.search do |search|
   search.status.is Braintree::Transaction::Status::Settled
end
```

Looping through `search_results` will always send another request to the server. Since `@ids` already contains the ids, why don't we just make it publicly accessible. For e.g: `search_result.ids`. I can try sending a pull request if you guys are OK with it

**Comment by crookedneighbor** [comment]
We don't expose it because it's not a normal use case to need the transaction ids separately from the transactions themselves. If the particulars of your project require it, you can always do `search_results.instance_variable_get("@ids")` to retrieve the array.

**Comment by eoinkelly** [comment]
FWIW having `#ids` be part of the public API would be useful for us too.

API searches return 20k results max so we are currently have code that splits the time period of our search into chunks if there are exactly 20k results for a given chunk. In this case it is convenient to work with the group if search result ids rather than the results themselves. We are using `instance_variable_get` but it would be more relaxing if it was part of public API :-)

**Comment by omgrr** [comment]
Happy to say that this feature went out today in 2.63.0 862f504b28130af4113e1d59f2a8242ddec92b44! You should be able to call `#ids` on any search result. Let us know if there are any issues.
