### ISSUE TITLE
Version specific Readme.md

### ISSUE THREAD

**Issue by shivabhusal** [braintree/braintree_ruby#116]
Hey!

I have noticed in many of the ruby libraries that they have maintained different version branches in their github repo. However `braintree_ruby` has only 3 branches and no version specific branches unlike

![image](https://cloud.githubusercontent.com/assets/8004593/15626157/1cb8fdde-24dd-11e6-8d3b-0f94cc7e58db.png)

### Advantages:
- I could see the particular version specific `Readme` documentation.
  - because with every major version release there is major changes in the API

What do you guys think about this?

**Comment by pblesi** [comment]
@shivabhusal We do not have separate versioned branches in our repo because we do not do active development on multiple versions of our client library at once, but always develop on our latest version of the library. You can view README files of our different versions by selecting "Tags" instead of "Branches" in the menu that you provided above.
