### ISSUE TITLE
Braintree::Transaction#refunded? returns true after a refund attempt failed

### ISSUE THREAD

**Issue by Rosa** [braintree/braintree_ruby#127]
We have observed that after a refund attempt has failed for some reason (in our case we saw a `Processor Network Unavailable` error), the `refunded?` method returns `true` for that transaction, even though it's not refunded. I suppose the cause is that this method just returns `true` based on the presence of a `refund_id`, regardless of it belonging to a successful refund transaction.

**Comment by mtmarsh3** [comment]
Hi @Rosa ,

Thanks for bringing this to our attention, we are currently looking into this and will get back to you soon.

**Comment by mtmarsh3** [comment]
Hi Rosa,
You're correct in that `refunded?` only checks for the status of `refund_id` and not whether the transaction was actually refunded. Since we allow for [partial refunds] (https://developers.braintreepayments.com/reference/request/transaction/refund/ruby#amount) for transactions, it's hard to provide a method to tell whether a transaction is refunded because it may not be fully refunded. 

To determine whether a transaction is refunded and by what amount, we recommend getting the [`refund_ids`](https://developers.braintreepayments.com/reference/response/transaction/ruby#refund_ids) of a transaction and calling [`Transaction.find`](https://developers.braintreepayments.com/reference/request/transaction/find/ruby) with each of the `refund_ids`. Then, check the [`status`](https://developers.braintreepayments.com/reference/response/transaction/ruby#status) attribute of each transaction to determine the state.

**Comment by Rosa** [comment]
@mtmarsh3 thanks for looking into this! What you said makes complete sense, I had forgotten about partial refunds. Using the `status` for each individual transaction was the solution I had already in mind, so thanks for confirming is the recommended one.
