### ISSUE TITLE
Documentation incorrect for using fake valid nonces with Subscription.create

### ISSUE THREAD

**Issue by mandysimon88** [braintree/braintree_ruby#162]
One cannot actually use any of the fake valid nonces listed on this 'Recurring billing' documentation page:
https://developers.braintreepayments.com/guides/recurring-billing/testing-go-live/ruby

Because of reasons listed here:
https://github.com/braintree/braintree_python/issues/86#issuecomment-294575976

Would be helpful to update the documentation to say that fake valid nonces CANNOT be used with Subscription.create.

The real solution to testing is what's used in this repo:
https://github.com/braintree/braintree_ruby/blob/master/spec/integration/braintree/client_api/spec_helper.rb

Maybe that solution has some flaw that it shouldn't be included in documentation, but at a minimum, the misleading documentation about `fake-valid-nonce` should be removed from the page about testing recurring billing.

Thank you!

**Comment by crookedneighbor** [comment]
Thanks for the feedback, I can see how that is confusing.

This is because the subscription must have a nonce that represents a vaulted payment method, which the fake valid ones do not. If you take the fake valid nonce and then create a vaulted payment method from them, then you can use that vaulted payment method to create the subscription.

I've passed on your feedback to our docs team. In the future, you can provide this feedback directly by using the "Give us Feedback on this Page" button at the bottom of each page.

Since this is not an issue with the SDK, I'm going to close this issue.

**Comment by mandysimon88** [comment]
Okay, thanks. It took me stumbling across the issue in the Python repo to realize that the fake-valid-nonces couldn't be used with Subscriptions for exactly the reason you describe.

Don't mind having the issue closed; someone can always dig through issues to find this if they're really stuck and determined (until the docs team gets to it ;-))

Thank you for forwarding it to them!

**Comment by yuvalt** [comment]
2.5 years later and it's still not documented 👎
