### ISSUE TITLE
Payment Method Create: Invalid Keys Verify Card Error 

### ISSUE THREAD

**Issue by SolomonBier** [braintree/braintree_ruby#86]
I'm getting the following error in sandbox trying to verify a credit card before it is added. This being pasted directly from docs

`ArgumentError (invalid keys: options[verify_card])`

    result = Braintree::PaymentMethod.create(
        :customer_id => "customer_id",
        :payment_method_nonce => params[:payment_method_nonce],
        :options => {
            :verify_card => true,
        }
    )

**Comment by SolomonBier** [comment]
This was an outdate gem. Updating to v `2.42.0` worked for me

**Comment by demonmind** [comment]
This is still happening on 2.56.0

**Comment by shock** [comment]
Happening for me on 2.57.0

**Comment by shock** [comment]
For any searchers who end up here, I thought this was happening for me on 2.57.0, but I realized I was calling `Braintree::Customer.create` (not PaymentMethod), which needs the `:verify_card` option wrapped inside the `:credit_card` key.  It's a little confusing, because `:payment_method_nonce` can be a top level key, or inside the `:credit_card` key.  If you want verification, put the nonce inside the `:credit_card` hash, as follows:

```ruby
    result = Braintree::Customer.create(
      :credit_card => {
        :payment_method_nonce => @nonce,
        :options => {:verify_card => true }
      }
    )
```
