### ISSUE TITLE
ApplePayCard has no reader method for @bin

### ISSUE THREAD

**Issue by josephsofaer** [braintree/braintree_ruby#87]
Here is a pull request (from Nov 2014) to add `@bin` to the list of readers.
https://github.com/braintree/braintree_ruby/pull/76

Does Braintree accept pull requests?

**Comment by dewyze** [comment]
@josephsofaer Braintree does accept PR's. However, as discussed in the PR you mentioned, the Apple Pay bin does not serve any purpose except to signify that it is an apple pay card. The card brand is available via the `card_type` reader method. The bin will not have any significance to a customer, and an ApplePayCard is not meant to be a drop-in replacement for a credit card. Additionally, in order to avoid other merchant's confusion with the real bin, we intentionally didn't include it.

Was there another reason you wanted to include a reader for the bin?

**Comment by dewyze** [comment]
@josephsofaer Closing this for now. Feel free to reopen if you have further questions.

**Comment by josephsofaer** [comment]
Thanks for your input. When Braintree first released ApplePay it was pitched as a drop-in payment method for merchants that had credit cards going. That was generally true but this was one of the only things that forced me to write branching code at the time.
All the best,
Joseph
